micronaut:
  application:
    name: micronautcrud
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=employee
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: '14003352@Fsk'
    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
jpa.default.properties.hibernate.hbm2ddl.auto: update
